W24TP/Models/Message.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W24TP.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Reponses = new HashSet<Reponse>();
        }
    
        public int MsgID { get; set; }
        public string MsgTitle { get; set; }
        [AllowHtml]
        public string MsgText { get; set; }
        public int CatID { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int View { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reponse> Reponses { get; set; }
    }
}

W24TP/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using W24TP.Models;

namespace W24TP.Controllers
{
    public class CategoriesController : Controller
    {
        private ForumONIEntities db = new ForumONIEntities();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.Select(cat => new CategoryDisplay
            {
                CatID = cat.CatID,
                CategoryName = cat.CategoryName,
                CreationDate = cat.CreationDate,
                User = cat.AspNetUser.UserName,
                IsActive = cat.IsActive,
                LastThreePosts = db.Messages
                        .Where(t => t.CatID == cat.CatID)
                        .OrderByDescending(t => t.CreationDate)
                        .Take(3).ToList(),
                Messages = db.Messages
                        .Where(t => t.CatID == cat.CatID)
                        .OrderByDescending(t => t.CreationDate)
                        .ToList()
            }).ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            return View(new CategoryDisplay
            {
                CatID = category.CatID,
                CategoryName = category.CategoryName,
                CreationDate = category.CreationDate,
                User = category.AspNetUser.UserName,
                IsActive = category.IsActive,
                LastThreePosts = db.Messages
                    .Where(t => t.CatID == category.CatID)
                    .OrderByDescending(t => t.CreationDate)
                    .Take(3).ToList(),
                Messages = db.Messages
                    .Where(t => t.CatID == category.CatID)
                    .OrderByDescending(t => t.CreationDate)
                    .ToList()
            });
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Categories/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CatID,CategoryName,IsActive,CreationDate,User")]
            Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", category.UserID);
            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", category.UserID);
            return View(category);
        }

        // POST: Categories/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CatID,CategoryName,IsActive,CreationDate,User")]
            Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", category.UserID);
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }

    public class CategoryDisplay
    {
        public int CatID { get; set; }
        public string CategoryName { get; set; }
        public DateTime CreationDate { get; set; }
        public string User { get; set; }
        public bool IsActive { get; set; }
        public List<Message> LastThreePosts { get; set; }
        public List<Message> Messages { get; set; }
    }
}

W24TP/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using W24TP.Models;

namespace W24TP.Controllers
{
    public class UsersController : Controller
    {
        private ForumONIEntities db = new ForumONIEntities();

        private static DateTime Max(DateTime first, DateTime second)
        {
            return first > second ? first : second;
        }

        // GET: Users
        public ActionResult Index()
        {
            return View(db.AspNetUsers.Select(yousir => new UserDisplay
            {
                UserID = yousir.Id,
                UserName = yousir.UserName,
                NbrSub = db.Messages.Count(t => t.UserID == yousir.Id),
                NbrRep = db.Reponses.Count(t => t.UserID == yousir.Id),
                LastDate = db.Messages
                    .Where(t => t.UserID == yousir.Id)
                    .Select(t => t.CreationDate)
                    .Union(db.Reponses
                        .Where(t => t.UserID == yousir.Id)
                        .Select(t => t.CreationDate))
                    .OrderByDescending(t => t)
                    .FirstOrDefault()
            }));
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AspNetUser yousir = db.AspNetUsers.Find(id);
            if (yousir == null)
            {
                return HttpNotFound();
            }

            return View(new UserDisplay
            {
                UserID = yousir.Id,
                UserName = yousir.UserName,
                NbrSub = db.Messages.Count(t => t.UserID == yousir.Id),
                NbrRep = db.Reponses.Count(t => t.UserID == yousir.Id),
                LastDate = db.Messages
                    .Where(t => t.UserID == yousir.Id)
                    .Select(t => t.CreationDate)
                    .Union(db.Reponses
                        .Where(t => t.UserID == yousir.Id)
                        .Select(t => t.CreationDate))
                    .OrderByDescending(t => t)
                    .FirstOrDefault()
            });
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include =
                "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")]
            AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }

            return View(aspNetUser);
        }

        // POST: Users/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include =
                "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")]
            AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }

            return View(aspNetUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }

    public class UserDisplay
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public int NbrSub { get; set; }
        public int NbrRep { get; set; }
        public DateTime? LastDate { get; set; }
    }
}

W24TP/Views/Messages/Create.cshtml
@model W24TP.Models.Message

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Message</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.MsgTitle, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.MsgTitle, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.MsgTitle, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MsgText, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.MsgText, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.MsgText, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CatID, "CatID", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("CatID", null, htmlAttributes: new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.CatID, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.UserID, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.CreationDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.View, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.View, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.View, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new {@class = "text-danger"})
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

W24TP/Views/Messages/Delete.cshtml
@model W24TP.Models.Message

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MsgTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MsgTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MsgText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MsgText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.View)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.View)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

W24TP/Views/Messages/Details.cshtml
@using Microsoft.AspNet.Identity
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@model W24TP.Controllers.PostDisplay
@{
    ViewBag.Title = "Details";
}

<p><a href="/@ViewBag.OldUrl">Back to list</a></p>

<div class="card border-primary">
    <div class="card-header clearfix">
        @if (User.Identity.GetUserId() == Model.UserID || User.IsInRole("Admin"))
        {
            <a class="btn btn-secondary float-lg-right" href="/Messages/Edit/@(Model.MsgID)" role="button">
                <i class="icon ion-md-create"></i>
            </a>
        }
        <div class="float-lg-left">
            <h2>@Model.MsgTitle</h2>
            <h6 class="text-muted card-subtitle">
                @W24TP.Helpers.PrettyDate.Print(Model.CreationDate) | By
                @Html.ActionLink(Model.User, "Details", "Users", new
                {
                    id = Model.UserID
                }, null) |
                @Html.ActionLink(Model.CategoryName, "Details", "Categories", new
                {
                    id = Model.CatID
                }, null)
            </h6>
        </div>
    </div>

    <div class="card-body">
        @Html.Raw(Model.MsgText)
    </div>

    <div class="card-footer text-muted">
        Viewed @Model.Views times | IsActive = @Model.IsActive
    </div>
</div>

@Html.PagedListPager(Model.RepliesList, page => Url.Action("Details", new
{
    id = Model.MsgID, path = ViewBag.OldUrl, page
}))

@foreach (var item in Model.RepliesList)
{
    <div class="card border-info" style="margin-top: 8px;">
        <div class="card-body">
            @Html.Raw(item.RepText)
        </div>
        <div class="card-footer text-muted">
            @W24TP.Helpers.PrettyDate.Print(item.CreationDate) by <span class="font-italic">@item.AspNetUser.UserName</span>
        </div>
    </div>
}

@Html.PagedListPager(Model.RepliesList, page => Url.Action("Details", new { id = Model.MsgID, path = ViewBag.OldUrl, page }))

@if (Request.IsAuthenticated)
{
    <form method="post" action="/Reponses/Create/@Model.MsgID?path=@ViewBag.OldUrl">
        @Html.AntiForgeryToken()
        <div class="card border-success" style="margin-top:8px">
            <div class="card-header clearfix" style="padding: 6px 20px">
                <p class="text-muted float-lg-left" style="margin: 0">Leave a Reply</p>
                <button type="submit" class="btn btn-sm btn-success float-lg-right">Send</button>
            </div>
            <div class="card-body" style="padding: 8px">
                <textarea name="reply"></textarea>
            </div>
        </div>
    </form>
}
else
{
    <div class="card border-danger" style="margin-top:30px">
        <div class="card-body">
            <p class="card-text">
                @Html.ActionLink("Log in", "Login", "Account") or
                @Html.ActionLink("create account", "Register", "Account") to reply
            </p>
        </div>
    </div>
}

W24TP/Views/Messages/Edit.cshtml
@model W24TP.Models.Message

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Message</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MsgID)
    @Html.HiddenFor(model => model.UserID)
    @Html.HiddenFor(model => model.CreationDate)
    @Html.HiddenFor(model => model.View)

    <div class="form-group">
        @Html.LabelFor(model => model.MsgTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MsgTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MsgTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MsgText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MsgText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MsgText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CatID, "CatID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CatID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CatID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Details", new { id = Model.MsgID, path = "Categories" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}